package com.bookmyshow.reportservice.repository;

import com.bookmyshow.reportservice.dto.BookingStatsDto;
import com.bookmyshow.reportservice.dto.RevenueStatsDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

@Repository
public class ReportRepositoryImpl implements ReportRepository {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Override
    public List<BookingStatsDto> getBookingStatistics() {
        // This query assumes you have 'movies' and 'bookings' tables.
        // It calculates the total number of bookings and tickets sold per movie.
        String sql = "SELECT m.title, COUNT(b.id) as total_bookings, SUM(b.number_of_tickets) as tickets_sold " +
                     "FROM movies m " +
                     "JOIN bookings b ON m.id = b.movie_id " +
                     "GROUP BY m.title " +
                     "ORDER BY total_bookings DESC";

        return jdbcTemplate.query(sql, new BookingStatsRowMapper());
    }

    @Override
    public List<RevenueStatsDto> getRevenueStatistics() {
        // This query calculates the total revenue generated by each movie.
        String sql = "SELECT m.title, SUM(b.total_amount) as total_revenue " +
                     "FROM movies m " +
                     "JOIN bookings b ON m.id = b.movie_id " +
                     "GROUP BY m.title " +
                     "ORDER BY total_revenue DESC";

        return jdbcTemplate.query(sql, new RevenueStatsRowMapper());
    }

    private static final class BookingStatsRowMapper implements RowMapper<BookingStatsDto> {
        @Override
        public BookingStatsDto mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new BookingStatsDto(
                    rs.getString("title"),
                    rs.getLong("total_bookings"),
                    rs.getLong("tickets_sold")
            );
        }
    }

    private static final class RevenueStatsRowMapper implements RowMapper<RevenueStatsDto> {
        @Override
        public RevenueStatsDto mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new RevenueStatsDto(
                    rs.getString("title"),
                    rs.getBigDecimal("total_revenue")
            );
        }
    }
}