spring.application.name=offer-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/offer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.springframework=INFO
logging.level.com.eventbook.offerservice=DEBUG
logging.file.name=logs/offer-service.log