spring.application.name=event-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/event_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:password} # It is recommended to use environment variables
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password= # Uncomment and set if your Redis has a password

# JWT Configuration
jwt.secret=PLEASE_REPLACE_WITH_THE_SAME_STRONG_SECRET_KEY_AS_IN_API_GATEWAY

logging.level.org.springframework=INFO
logging.level.com.eventbook.eventservice=DEBUG
logging.file.name=logs/event-service.log